// This file was generated by lezer-generator. You probably shouldn't edit it.
export const Identifier = 1;
export const BlockComment = 2;
export const Bool = 3;
export const Type = 4;
export const Keyword = 5;
export const Null = 6;
export const Builtin = 7;
export const LineComment = 8;
export const Program = 9;
export const DateTime = 11;
export const Info = 12;
export const Warning = 13;
export const Error = 14;
export const String = 15;
export const Number = 16;
export const ErrorMsg = 17;
