// This file was generated by lezer-generator. You probably shouldn't edit it.
import { LRParser } from '@lezer/lr';
import { otherTokens } from './tokens';

export const parser = LRParser.deserialize({
  version: 14,
  states:
    "!^Q]QROOObQRO'#CfOOQQ'#Cn'#CnQ]QROOOmQRO,59QOOQQ-E6l-E6lOOQQ'#Cs'#CsOOQQ'#Co'#CoO{QRO1G.lOOQQ-E6m-E6m",
  stateData:
    '!g~OfOSWOSQOS~OZPO~O[SO]SO^SO~OPUO_UO`UOaUO~OPUO_UO`UOaUOZYidYi~OZ`a^a~',
  goto: '}hPPPPPPPPPPiPPPPPPPmsPPPyTQORQRORTRQWSRXWTVSW',
  nodeNames:
    '⚠ Identifier BlockComment Bool Type Keyword Null Builtin LineComment Program Message DateTime Info Warning Error String Number ErrorMsg',
  maxTerm: 23,
  skippedNodes: [0, 2, 3, 4, 5, 6, 7, 8],
  repeatNodeCount: 2,
  tokenData:
    "*R~RYXYqYZq]^qpqqrs!S}!O#p!Q![$_!g!h'f!k!l(o!y!z)W~vSf~XYqYZq]^qpqq~!VVOr!Srs!ls#O!S#O#P!q#P;'S!S;'S;=`#j<%lO!S~!qO_~~!tRO;'S!S;'S;=`!};=`O!S~#QWOr!Srs!ls#O!S#O#P!q#P;'S!S;'S;=`#j;=`<%l!S<%lO!S~#mP;=`<%l!S~#sP}!O#v~#{SW~OY#vZ;'S#v;'S;=`$X<%lO#v~$[P;=`<%l#v~$dQ`~}!O$j!Q![$_~$mP!Q![$p~$sQ}!O$y!Q![$p~$|P!Q![%P~%SQpq%Y!Q![%P~%]P!Q![%`~%cQ!Q![%`![!]%i~%lP!Q![%o~%rQ!Q![%o![!]%x~%{P!Q![&O~&RQ!Q![&O!}#O&X~&[P!i!j&_~&bP!o!p&e~&hP!v!w&k~&nP{|&q~&tP!Q![&w~&zQ!Q![&w![!]'Q~'TP!Q!['W~'ZQ!Q!['W#P#Q'a~'fOZ~~'iP!t!u'l~'oP!t!u'r~'uP!q!r'x~'{P!t!u(O~(TP^~#R#S(W~(ZP!o!p(^~(aP!u!v(d~(gP!i!j(j~(oOa~~(rP!p!q(u~(xP!h!i({~)OP!q!r)R~)WO[~~)ZP!c!d)^~)aP!t!u)d~)gP!p!q)j~)mP!k!l)p~)sP!p!q)v~)yP!i!j)|~*RO]~",
  tokenizers: [0, otherTokens],
  topRules: { Program: [0, 9] },
  tokenPrec: 63,
});
